"""update table post1

Revision ID: 0ae30375f6f3
Revises: a5e9e8ddb221
Create Date: 2017-08-17 10:20:20.041167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae30375f6f3'
down_revision = 'a5e9e8ddb221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
